# =============================================================================
# screenshot_specs.R
# Which parts of the console transcripts (type = "console"), scripts
# (type = "source"), logs (type = "textfile") or HTML outputs (type = "html")
# are rendered as screenshots by render_screenshots.R.
#   sections: numbered "# ---- x.y Title ----" headers of the analysis scripts
#   parts:    list(section, from = regex, until = regex) for shorter excerpts
# A spec is skipped when its source file does not exist (e.g. in the Week 1
# repository, which does not contain the Week 3 scripts).
# =============================================================================
p <- function(section, from = NULL, until = NULL) list(section = section, from = from, until = until)

screenshot_specs <- list(
  # ---- Week 1: data import, cleaning and preliminary analysis ----
  list(id = "w1_ss01_dataset_import", week = 1, type = "console", log = "01_data_import",
       sections = c("1.1", "1.2"), title = "Download check, import, dim() and names()"),
  list(id = "w1_ss02_head_tail", week = 1, type = "console", log = "01_data_import",
       parts = list(p("1.3", from = "^> # Compact view")), title = "head() and tail() of eight key columns"),
  list(id = "w1_ss02b_head_tail_full", week = 1, type = "console", log = "01_data_import",
       parts = list(p("1.3", until = "^> # Compact view")), title = "head() and tail() of all 21 columns"),
  list(id = "w1_ss03_str_raw", week = 1, type = "console", log = "01_data_import",
       sections = "1.4", title = "str() of the raw data"),
  list(id = "w1_ss04_summary_raw", week = 1, type = "console", log = "01_data_import",
       sections = "1.5", title = "summary() of the raw data"),
  list(id = "w1_ss05_type_check", week = 1, type = "console", log = "01_data_import",
       parts = list(p("1.6", until = "^> save_table")), title = "Data type check"),
  list(id = "w1_ss06_totalcharges_duplicates", week = 1, type = "console", log = "01_data_import",
       parts = list(p("1.6", from = "^> # TotalCharges was read", until = "^> # SeniorCitizen"),
                    p("1.7", until = "^> dup_profiles %>%")),
       title = "TotalCharges raw values and duplicate checks"),
  list(id = "w1_ss07_missing_values", week = 1, type = "console", log = "02_data_cleaning",
       sections = "2.2", title = "Missing values per column (count and %)"),
  list(id = "w1_ss08_missing_pattern", week = 1, type = "console", log = "02_data_cleaning",
       sections = "2.4", title = "Pattern of the missing TotalCharges values"),
  list(id = "w1_ss09_missing_treatment", week = 1, type = "console", log = "02_data_cleaning",
       sections = "2.5", title = "Missing-value treatment: options and before/after check"),
  list(id = "w1_ss10_type_conversion", week = 1, type = "console", log = "02_data_cleaning",
       parts = list(p("2.3"), p("2.7", from = "^> # Converting to factors")),
       title = "Type conversion and factor checks"),
  list(id = "w1_ss11_str_clean", week = 1, type = "console", log = "02_data_cleaning",
       parts = list(p("2.8", until = "^> summary\\(telco\\)")), title = "str() of the cleaned data"),
  list(id = "w1_ss12_summary_clean", week = 1, type = "console", log = "02_data_cleaning",
       parts = list(p("2.8", from = "^> summary\\(telco\\)"), p("2.9")),
       title = "summary() of the cleaned data and validation checks"),
  list(id = "w1_ss13_outliers_iqr_z", week = 1, type = "console", log = "03_eda",
       sections = c("3.1", "3.2"), title = "Outlier detection: IQR rule and z-scores"),
  list(id = "w1_ss14_outliers_context", week = 1, type = "console", log = "03_eda",
       parts = list(p("3.3", from = "^> # Points beyond the whiskers", until = "^> save_table"),
                    p("3.4", until = "^> telco_chk <- telco_chk"), p("3.6", from = "^> outlier_decision$")),
       title = "Group-wise and contextual outlier checks, treatment decision"),
  list(id = "w1_ss15_scaling", week = 1, type = "console", log = "03_eda",
       parts = list(p("3.7", until = "^> # Scaling changes the units")),
       title = "Min-max normalisation and z-score standardisation"),
  list(id = "w1_ss16_encoding", week = 1, type = "console", log = "03_eda",
       parts = list(p("3.8", from = "^> x_design <-", until = "^> encoded <-")),
       title = "Dummy and one-hot encoding, redundancy check"),
  list(id = "w1_ss17_descriptive", week = 1, type = "console", log = "03_eda",
       parts = list(p("3.9", from = "^> print\\(desc_numeric", until = "^> skim_out")),
       title = "Descriptive statistics: summaries by churn, mean(), median(), sd(), quantile()"),
  list(id = "w1_ss18_frequencies", week = 1, type = "console", log = "03_eda",
       parts = list(p("3.10", until = "^> save_table\\(cat_freq")), title = "table() frequencies and churn by category"),
  list(id = "w1_ss19_correlation", week = 1, type = "console", log = "03_eda",
       parts = list(p("3.12", until = "^> save_table"), p("3.12", from = "^> cramers_v %>%", until = "^> save_table\\(cramers_v")),
       title = "Pearson and Spearman correlation matrices, Cramer's V"),

  # ---- Week 2: visualisation ----
  list(id = "w2_ss01_code_bar_chart", week = 2, type = "source", file = "R/04_visualization.R",
       sections = "4.1", title = "ggplot2 code for the bar chart (V1)"),
  list(id = "w2_ss02_code_line_chart", week = 2, type = "source", file = "R/04_visualization.R",
       sections = "4.4", title = "ggplot2 code for the line chart (V4)"),
  list(id = "w2_ss03_console_bar_scatter", week = 2, type = "console", log = "04_visualization",
       parts = list(p("4.1", from = "^> v1_data$", until = "^> v1 <-"),
                    p("4.2", from = "^> v2_summary$", until = "^> facet_names"),
                    p("4.3", from = "^> v3_summary$", until = "^> v3 <-")),
       title = "Data behind the bar chart, scatter plot and histogram"),
  list(id = "w2_ss04_console_line_chart", week = 2, type = "console", log = "04_visualization",
       parts = list(p("4.4", from = "^> print\\(v4_data", until = "^> min_n")), max_chars = 104,
       title = "Churn rate by tenure band and contract (data for V4)"),
  list(id = "w2_ss05_console_additional", week = 2, type = "console", log = "04_visualization",
       parts = list(p("4.6", from = "^> a2_data$", until = "^> a2_order"),
                    p("4.8", from = "^> a4_summary$", until = "^> a4 <-"),
                    p("4.9", from = "^> a5_data$", until = "^> a5 <-")),
       title = "Data behind the stacked bar, box/violin and heatmap"),
  list(id = "w2_ss06_console_saved_figures", week = 2, type = "console", log = "04_visualization",
       parts = list(p("4.10", from = "^> a6_data$"), p("4.11", from = "^> a7_summary$")),
       title = "Add-on and tenure-outlier summaries; figures written by ggsave()"),
  list(id = "w2_ss07_interactive_chart", week = 2, type = "html",
       file = "outputs/interactive/w2_interactive_scatter.html", width = 900, height = 520,
       title = "Interactive plotly version of the scatter plot"),

  # ---- Week 3: statistics and modelling ----
  list(id = "w3_ss00_summary_statistics", week = 3, type = "console", log = "05_statistical_analysis",
       sections = "5.1", title = "Class balance and summary statistics by churn status"),
  list(id = "w3_ss01_normality_variance", week = 3, type = "console", log = "05_statistical_analysis",
       parts = list(p("5.2", from = "^> normality$", until = "^> qq_data"),
                    p("5.3", from = "^> levene_mc_churn$")),
       title = "Normality (Anderson-Darling, Shapiro-Wilk) and Levene tests"),
  list(id = "w3_ss02_chisq_contract", week = 3, type = "console", log = "05_statistical_analysis",
       sections = "5.4", title = "H1: chi-square test, contract type vs churn"),
  list(id = "w3_ss03_ttest_wilcoxon", week = 3, type = "console", log = "05_statistical_analysis",
       parts = list(p("5.5", from = "^> h2 <-", until = "^> h2_means <-"),
                    p("5.5", from = "^> h2_w <-"), p("5.6", from = "^> h3 <-", until = "^> n_no")),
       title = "H2 Welch t-test and H3 Wilcoxon rank-sum tests"),
  list(id = "w3_ss04_anova", week = 3, type = "console", log = "05_statistical_analysis",
       parts = list(p("5.7", from = "^> summary\\(h4_aov", until = "^> pairwise")),
       title = "H4: ANOVA, Welch ANOVA and Kruskal-Wallis"),
  list(id = "w3_ss05_test_summary", week = 3, type = "console", log = "05_statistical_analysis",
       parts = list(p("5.12", from = "^> print\\(test_summary")), title = "All hypothesis tests with Holm-adjusted p-values"),
  list(id = "w3_ss06_split_vif", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.2", from = "^> c\\(train"),
                    p("6.3", from = "^> round\\(vif_all", until = "^> # Interpretable logistic")),
       title = "Stratified split and VIF check with all predictors"),
  list(id = "w3_ss06b_vif_reduced_folds", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.3", from = "^> # Interpretable logistic"), p("6.4", from = "^> sapply")),
       title = "VIF of the reduced logistic model and churn rate per CV fold"),
  list(id = "w3_ss07_training_logistic", week = 3, type = "console", log = "06_predictive_model",
       sections = "6.5", title = "Model 1 training: logistic regression with 10-fold CV"),
  list(id = "w3_ss08_logistic_summary", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.6", from = "^> summary\\(glm_lr", until = "^> or_table <-")),
       title = "Model 1 summary: glm coefficients"),
  list(id = "w3_ss09_training_rf", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.7", from = "^> model_rf$", until = "^> p_tune")),
       title = "Model 2 training: random forest tuning with 10-fold CV"),
  list(id = "w3_ss10_cv_comparison", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.8", from = "^> summary\\(cv_results", until = "^> cv_summary <-")),
       title = "Cross-validated comparison of the models"),
  list(id = "w3_ss11_confusion_logistic", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.9", from = "^> cm_lr$", until = "^> cm_rf$")),
       title = "Confusion matrix and statistics: logistic regression (test set)"),
  list(id = "w3_ss12_confusion_rf_auc", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.9", from = "^> cm_rf$", until = "^> metrics_row <-")),
       title = "Confusion matrix (random forest), ROC-AUC and DeLong test"),
  list(id = "w3_ss13_threshold_metrics", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.12", from = "^> best_thr <-", until = "^> save_table\\(bind_rows"),
                    p("6.12", from = "^> cm_lr_t\\$table", until = "^> save_table\\(test_metrics_all")),
       title = "Threshold chosen on out-of-fold predictions and test-set metrics"),
  list(id = "w3_ss14_diagnostics", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.13", from = "^> hl$", until = "^> binned <-"),
                    p("6.13", from = "^> sum\\(abs", until = "^> p_binned"),
                    p("6.13", from = "^> print\\(calib", until = "^> save_table\\(calib")),
       title = "Diagnostics: Hosmer-Lemeshow, Cook's distance, binned residuals, calibration"),
  list(id = "w3_ss15_importance_gains", week = 3, type = "console", log = "06_predictive_model",
       parts = list(p("6.14", from = "^> print\\(rf_imp", until = "^> save_table\\(rf_imp"),
                    p("6.15", from = "^> gains_summary$", until = "^> save_table")),
       title = "Random forest permutation importance and cumulative gains"),

  # ---- Every repository: summary of the complete pipeline run ----
  list(id = "pipeline_run", week = NA, type = "textfile", file = "outputs/logs/run_all_console.txt",
       title = "Complete pipeline run (run_all.R)"),

  # ---- Week 4: integrated analysis ----
  list(id = "w4_ss02_driver_evidence", week = 4, type = "console", log = "07_final_analysis",
       parts = list(p("7.1", from = "^> print\\(driver_evidence", until = "^> save_table")),
       max_chars = 104, title = "Driver evidence combined across Weeks 1-3"),
  list(id = "w4_ss03_segments_deciles", week = 4, type = "console", log = "07_final_analysis",
       parts = list(p("7.2", from = "^> print\\(segments", until = "^> save_table"),
                    p("7.3", from = "^> print\\(deciles", until = "^> save_table")),
       title = "Customer segments and predicted-risk deciles"),
  list(id = "w4_ss04_headline", week = 4, type = "console", log = "07_final_analysis",
       parts = list(p("7.4", from = "^> headline$", until = "^> save_table")),
       title = "Headline numbers for the final report")
)
